### ISSUE TITLE
Wrong in helppage for chart

### ISSUE THREAD

**Issue by JimAlexBerger** [kometh0616/fmcord#7]
In the note for the help page of chart, it says "In time period, you can have "weekly", "monthly" or "overall"".

In your source code it looks like the options are weekly, monthly and alltime.

So i guess the fix is replace overall in the help page with alltime

**Comment by kometh0616** [comment]
Good afternoon, JimAlexBerger,

This issue is addressed in the latest commit. Now, the help command should show "alltime" as an option, instead of "overall".
Thank you for pointing this out.

Regards
-Kometh
