### ISSUE TITLE
Bot responds to `&<command>` despite its prefix being changed to something else

### ISSUE THREAD

**Issue by d-shaun** [kometh0616/fmcord#8]
Steps to reproduce:
* Change prefix: `&prefix set >`
* Now, run any command with the prefix `&` or `>`: `&l a w` or `>l a w`—bot responds to both of them.

**Comment by kometh0616** [comment]
It is meant to be this way. Prefix `&` is meant to work everywhere. This is in case people don't know what prefix is set in a certain guild or can't be bothered to memorize them all.

**Comment by d-shaun** [comment]
Uhm... so, it's just **adding** another prefix instead of **setting** a prefix; what would be the point of changing the bot's prefix if not to avoid _theoretically_ having two bots respond to the same prefix?

**Comment by kometh0616** [comment]
You can use the added prefix instead.
The default prefix is left there in emergency cases (prefix being forgotten, added prefix not working, etc.)

**Comment by d-shaun** [comment]
I get what you mean, but this makes very little practical sense to me.
There are better ways to get around the emergency case issue. If you moderate a guild: you can put the prefix in the bot's nickname. If you are a "normal" user: you can ask a mod. Or, a much simpler way is to simply @mention the bot and it gives you the prefix.
I think having two prefixes makes things tangled, if anything.

**Comment by kometh0616** [comment]
I will see about an ability to disable the default prefix completely.
In the meantime, have you tried to change prefix in the other bot?
